language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=StackableFinder
    - REQUIRE=""
    - DB=mysql
    - CAKE_REF=2.7.8

  matrix:
    - 
    - CAKE_REF=2.6.12

matrix:
  include:
    - php: 5.3
      env:
        - DB=pgsql
    - php: 5.3
      env:
        - DB=sqlite
    - php: 5.3
      env:
        - COVERALLS=1
    - php: 5.3
      env:
        - PHPCS=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
